name: Website Monitor

on:
  schedule:
    - cron: '0 7 * * *'  # Runs every day at 07:00 UTC
  workflow_dispatch:      # Allows manual runs

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Show Python and pip version
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run monitor script
        run: python monitor.py

      - name: Switch to monitor-output branch and copy output files
        run: |
          git fetch origin monitor-output:monitor-output || true
          git checkout monitor-output || (
            git checkout --orphan monitor-output
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit --allow-empty -m "init"
          )
          git checkout main -- hashes.json previous_content.json change_history.json docs/index.md

      - name: Commit hash updates and dashboard to monitor-output
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add hashes.json previous_content.json change_history.json docs/index.md
          git commit -m "Update hashes, content, and dashboard" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
          git push origin monitor-output
